DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS maps CASCADE;
DROP TABLE IF EXISTS owners CASCADE;
DROP TABLE IF EXISTS favourites CASCADE;
DROP TABLE IF EXISTS points CASCADE;

CREATE TABLE users (
	id SERIAL PRIMARY KEY NOT NULL,
	email VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,
	profile_photo VARCHAR(255),
	username VARCHAR(20) NOT NULL
);

CREATE TABLE maps (
	id SERIAL PRIMARY KEY NOT NULL,
	name VARCHAR(255) NOT NULL,
	public_edits BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE owners (
	owner_id REFERENCES users(id) ON DELETE CASCADE,
	map_id REFERENCES maps(id) ON DELETE CASCADE
);

CREATE TABLE favourites (
	user_id REFERENCES users(id) ON DELETE CASCADE,
	map_id REFERENCES maps(id) ON DELETE CASCADE
);

CREATE TABLE points (
	creator_id REFERENCES users(id) ON DELETE CASCADE,
	map_id REFERENCES maps(id) ON DELETE CASCADE,
	title VARCHAR(255) NOT NULL,
	description TEXT NOT NULL,
	image VARCHAR(255) NOT NULL,
	longitude SMALLINT NOT NULL,
	latitude SMALLINT NOT NULL
);
